import React from 'react'

export default function bt6() {
  return (
    <div className='w-[500px] h-[200px] overflow-auto'>
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum quis dicta ex nemo dolor eveniet magnam blanditiis atque sunt? Labore ex soluta fugiat distinctio veritatis illum sint dolorum quia explicabo.
      Nobis, atque aperiam. Tempore, eius! Est saepe voluptas officia perferendis blanditiis debitis reprehenderit nulla numquam, minima quam quae, necessitatibus, qui quod ea labore sit velit unde deleniti placeat. Praesentium, rem?
      Ad officiis quisquam quaerat beatae maiores, corrupti cumque voluptas harum labore consectetur cum vel, pariatur error expedita. Doloremque obcaecati quos animi nam tempore iure esse dolorem expedita repudiandae, quaerat pariatur.
      Fugit porro, quis libero ea mollitia sapiente autem adipisci exercitationem ducimus nobis similique accusantium deserunt magnam dolores. Quisquam exercitationem, odit tempora architecto facilis illum quas nemo debitis sequi amet repudiandae.
      Quibusdam tempora nemo error. Consectetur cumque quaerat repellendus assumenda ullam perspiciatis at minus nesciunt dolores quos, adipisci vero quibusdam, consequatur mollitia commodi esse, corporis et sunt molestias eligendi! Cumque, quo.
      Eum nihil quod repudiandae atque. Atque nulla autem aut ducimus exercitationem iusto eum assumenda veniam, pariatur, dolores ipsam cum sapiente nam labore repudiandae magni aperiam quibusdam quas enim laborum architecto.
      Consequatur reiciendis numquam fugit, veritatis consequuntur vero deleniti delectus nisi illo id. Tenetur est enim nostrum animi, sint iusto fugit, iste nam laboriosam, vitae dignissimos perferendis ab beatae voluptates aperiam!
      Veniam consequuntur, quam cum quasi minus deserunt eveniet quae voluptatem accusantium illum rem quas tempora ipsum ducimus, impedit atque repellendus quo itaque maxime quidem sed non commodi. Voluptatem, molestiae beatae?
      Vitae, autem fugit delectus, ut dolore aut alias officiis saepe perferendis ullam officia ipsa nam iusto a necessitatibus nulla dignissimos facilis perspiciatis ab. Praesentium sint sit quam explicabo voluptatum omnis?
      Aliquam odit tenetur consequatur distinctio impedit. Sunt distinctio inventore consectetur, fuga quia atque. Quos fuga, quis error deleniti iure eveniet odit, libero nulla necessitatibus rem voluptates cupiditate nisi culpa sit.
      Fugit reprehenderit eum maxime voluptas ducimus impedit id excepturi cumque quidem aut hic tempora consequatur nam nesciunt, facilis obcaecati quaerat, ullam magni officiis odit animi pariatur? Facere eos placeat saepe?
      Voluptate optio commodi deserunt saepe est enim minima molestias, laudantium, rerum provident quibusdam temporibus voluptates repellat adipisci culpa obcaecati, tempore esse repudiandae? Quos vel, facere dolorem deserunt tempore at illum?
      Impedit in architecto dolorem numquam qui enim molestiae eaque dolorum repellat. Inventore in soluta, veniam asperiores architecto rem hic deserunt quisquam aut dolor dolorem amet accusamus, voluptatibus eos, aliquam recusandae!
      Illo quibusdam magni sint non illum ducimus iste. Sequi dolorem reprehenderit, est dignissimos exercitationem aperiam possimus incidunt magnam, fugit eveniet, recusandae error itaque nulla doloremque optio? Excepturi magnam ipsa ratione.
      Vitae minima in harum aut repellendus illo laudantium ut omnis. Eius incidunt autem qui facere nesciunt earum, illo nostrum. Quas dignissimos quod aut fugiat perferendis voluptate vitae aliquid nam unde?
      Incidunt, sed, itaque aliquam neque odit voluptatem illo quo aspernatur eligendi officiis voluptatum? Natus, laudantium mollitia. Saepe, debitis delectus, reiciendis temporibus quis id totam odit at, minus dignissimos sed laborum.
      Voluptas autem itaque eum iusto ut minima dolore, corrupti quaerat aliquam, fugit nisi harum! Esse accusantium inventore ipsam pariatur maiores, sint, magnam distinctio dolorem sapiente debitis in, sequi magni impedit?
      Doloremque ullam accusantium officia repellat aut perspiciatis, dolor necessitatibus ratione itaque eligendi magni quas tempora ea obcaecati culpa ipsum magnam aliquid sint distinctio laudantium sequi nesciunt similique et blanditiis? Sed.
      Eum quos culpa aliquam blanditiis quasi possimus voluptatum nemo cum debitis itaque suscipit, placeat nisi voluptate eos praesentium obcaecati necessitatibus, maxime, esse autem sint. At veritatis consequatur dolores quaerat natus.
      Quo quisquam enim reiciendis quibusdam suscipit veritatis distinctio repudiandae consectetur cumque laboriosam. Omnis unde autem a labore, repudiandae doloribus, totam ab, fuga voluptas quo ipsum consectetur enim? Officiis, ratione facilis.
      Autem consequatur doloribus suscipit quae voluptatem possimus hic architecto neque cumque dignissimos commodi dolore, distinctio asperiores nesciunt modi quam beatae sunt eum. Blanditiis minima aliquid incidunt rerum beatae doloribus unde.
      Doloremque suscipit, nemo sapiente autem sint laboriosam quia consectetur modi ex aspernatur tempora placeat enim non nam, facere aliquid adipisci quo cupiditate totam? Iste animi voluptas consequuntur eligendi minima odit!
      Laboriosam ducimus accusantium possimus reprehenderit repellendus sequi, alias porro distinctio quo error voluptas rem! Magnam dolore sint, earum provident possimus quisquam cumque sunt, dignissimos natus excepturi id quidem, fugiat deserunt.
      Repudiandae culpa recusandae, est blanditiis quia quasi aliquam dolorum eligendi quas iste perferendis quo excepturi doloribus non quae. Officia totam minima beatae ad, hic consequuntur corrupti maxime error reprehenderit fugit.
      Cupiditate similique amet minima id? Natus odio quis ipsam autem nemo maxime facilis nostrum. Nemo, dolores similique. Architecto, animi error nulla maxime aliquam, aut voluptatibus, sapiente distinctio natus consequatur qui.
      Veniam aperiam corrupti sint architecto quisquam iusto totam non autem porro quis quos, voluptatem ipsam praesentium saepe voluptatibus! Quam aut id nam totam voluptas. Eligendi consectetur soluta ad accusamus obcaecati!
      In esse sit, tempora dolores incidunt sint odio, dicta libero eius repellendus eaque? Quae, soluta, distinctio alias eum quod expedita deserunt velit neque minima doloribus praesentium. Error itaque quaerat quas!
      Architecto beatae voluptatem id culpa molestiae ut eos illum nemo dignissimos aliquid veniam eaque, consequatur necessitatibus quod laborum, totam fuga voluptates exercitationem sapiente dolor. Distinctio, dolorum. Perspiciatis earum fugiat velit?
      Quisquam sunt veritatis debitis distinctio quos quibusdam ipsa. Omnis vel minima rem doloribus vero, soluta voluptate. Aut vero quidem ex, pariatur assumenda possimus explicabo veniam a saepe numquam totam consectetur!
      Quibusdam optio eveniet dolor eos laborum, dolorum, quod repudiandae perspiciatis, at sapiente molestiae. Natus quo qui maiores architecto quod vel vero laborum, impedit voluptates pariatur esse sed ratione ad reprehenderit.
      Est magnam porro fugit voluptatum consequatur? Nisi sit laborum nesciunt vero natus eveniet soluta doloremque, aspernatur quos nobis, consequatur ullam ratione asperiores. Aliquam cum iusto consequatur, enim dolores accusamus illum!
      Ducimus fugiat commodi, aliquid et dolorem minus sunt reprehenderit ut, necessitatibus exercitationem libero ratione molestiae obcaecati. Quaerat cumque culpa illo, blanditiis officiis quasi placeat debitis nihil expedita! Asperiores, nostrum odit?
      Sequi dignissimos beatae enim? Nisi et magni harum iusto iure suscipit. Perspiciatis maxime laborum aliquam laboriosam odio molestias excepturi consequuntur possimus, doloremque incidunt itaque in optio nobis nisi labore nemo.
      Repudiandae fugiat quaerat eius, debitis molestias ad esse maxime fugit assumenda? Assumenda eligendi facilis accusamus ratione, molestiae quaerat ipsam unde excepturi eum cum nesciunt molestias tempore quisquam distinctio quibusdam qui.
      Dolorum mollitia reiciendis dicta deleniti culpa maiores aspernatur sequi. Perferendis impedit quibusdam dolorem, in alias temporibus qui, est voluptatum voluptate obcaecati suscipit quaerat reprehenderit, nesciunt possimus culpa asperiores dignissimos fugiat.
      Maxime est consequuntur dignissimos explicabo aperiam labore atque placeat, eveniet dicta perferendis iste doloribus iusto error accusantium autem hic quibusdam ullam reiciendis quisquam vel repudiandae. Voluptatibus optio quidem dolorem saepe.
      Praesentium necessitatibus nam repellat, quidem, aspernatur dolor molestiae facere illum deleniti alias rem cupiditate unde optio cum, culpa quos velit ea iste suscipit doloribus. Rerum in error distinctio omnis optio?
      Culpa repellat doloremque assumenda nam facere fugit libero odit placeat doloribus eum aliquam reiciendis ipsa quidem officia dicta, provident voluptas ipsam porro? Illum qui, aspernatur modi maxime expedita veritatis! Unde.
      Illum molestias eligendi voluptate facere nulla tempore vero ipsum quas nobis error praesentium provident adipisci, possimus maxime! Odit sequi necessitatibus exercitationem, laboriosam tempore culpa earum cumque debitis amet minus id?
      Alias eos consectetur saepe est, animi aperiam ducimus quibusdam accusantium, porro inventore voluptatem atque in laboriosam odit, ipsam officia eaque ab soluta aliquid? Quo voluptates natus veritatis pariatur, vel quidem.
      Sit est architecto eligendi impedit quasi magni deserunt commodi ad ratione neque doloremque blanditiis mollitia temporibus ea placeat consectetur, numquam maxime at! Iusto ea eligendi esse doloremque sed eius similique.
      Libero hic veniam, eum accusantium illo eligendi deserunt corrupti rem asperiores deleniti minus officia repellendus nihil consectetur fuga, eaque, at atque. Saepe quisquam facilis eveniet. Ab ut porro repellat quae!
      Nemo illo iste perferendis consequuntur, dolor ex cum placeat dolore recusandae modi magnam officia dolores id molestiae voluptate nesciunt sunt sed. Quos laudantium voluptates vitae libero expedita excepturi odit est!
      Iusto facere expedita exercitationem harum modi aspernatur eum blanditiis optio quas, tempore repudiandae nihil, quod quidem aliquid placeat alias earum et quis enim. Qui voluptatem officiis beatae quidem sequi quibusdam!
      Debitis nam nostrum error vel ex ipsum numquam sapiente perspiciatis et? Nemo amet perspiciatis numquam modi, non expedita repudiandae, dolor vitae, est itaque a nam sequi porro. Sequi, commodi dolor.
      Quam nulla dolore enim totam optio doloribus alias nisi harum minima illo aliquid iusto nemo magni eos praesentium, sit voluptas debitis numquam quas quaerat unde distinctio laboriosam, explicabo illum? Eos.
      Quis sit hic rerum, consequuntur recusandae ducimus earum tempore sunt vel iure cumque voluptas ipsa fugiat, delectus autem quam aliquid! Modi tempora mollitia dignissimos distinctio vitae dicta explicabo quam sint.
      Quae illum nesciunt et nemo aspernatur accusantium odio a! Nisi quo nemo qui adipisci voluptate, labore id unde veniam iusto dolores excepturi reprehenderit accusamus sapiente ad dolorem repellendus. Veritatis, ex.
      Magni nam pariatur debitis iusto eaque alias sequi sunt, commodi magnam cumque quas nisi, nesciunt consequatur deserunt consectetur et autem fugiat soluta perspiciatis nulla, molestias facere ullam dolorum saepe? Deserunt.
      Laboriosam maiores facilis optio ipsa quia labore repellendus, quod obcaecati ratione fugiat pariatur necessitatibus tempora magnam fugit minima dolores dolore eos doloremque officiis tenetur esse recusandae natus in accusantium. Quo.
    </div>
  )
}